// =======================================================
// 🚀 Firebase Options (Generated by FlutterFire CLI)
// =======================================================
// File ini otomatis dibuat oleh FlutterFire CLI.
// Saya cuma nambah komentar, emote, ASCII, dan print()
// LOGIC ASLI AMAN & TIDAK DIUTAK-ATIK ❌
//
// WARNING:
// - API key di sini adalah client-side config
// - BUKAN service account (jangan panik dulu 😌)
// - Tapi tetap jangan sembarang upload repo 🔒
//
// =======================================================
//
//   🔥 FIREBASE ZONE 🔥
//
//   ( ͡° ͜ʖ ͡°)
//    <| Firebase |
//    / \
//
// =======================================================

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] untuk dipakai di app kamu.
///
/// Contoh penggunaan:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// Catatan hidup:
/// - Ganti project? Jalankan `flutterfire configure`
/// - Jangan cuma rename folder 😅
class DefaultFirebaseOptions {

  // ===================================================
  // 🧠 Deteksi Platform
  // ===================================================
  // Firebase mikir:
  // "Aku lagi jalan di mana ya?" 🤔
  static FirebaseOptions get currentPlatform {
    print("");
    print("🔥 ================================");
    print("🔥 Firebase: Deteksi platform...");
    print("🔥 kIsWeb: $kIsWeb");
    print("🔥 Platform: $defaultTargetPlatform");
    print("🔥 ================================");
    print("");

    if (kIsWeb) {
      print("🌐 Firebase pakai konfigurasi WEB");
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        print("🤖 Firebase pakai konfigurasi ANDROID");
        return android;

      case TargetPlatform.iOS:
        print("🍎 Firebase pakai konfigurasi iOS");
        return ios;

      case TargetPlatform.macOS:
        print("💻 Firebase pakai konfigurasi macOS");
        return macos;

      case TargetPlatform.windows:
        print("🪟 Firebase pakai konfigurasi WINDOWS");
        return windows;

      case TargetPlatform.linux:
        print("🐧 Linux belum dikonfigurasi!");
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux. '
              'Run FlutterFire CLI again.',
        );

      default:
        print("🤷 Platform tidak dikenal oleh Firebase");
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // =============================
  // 🌐 WEB
  // =============================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxrg3As4P9q7uHd1anjZPglHB2HH6mf6k',
    appId: '1:199751335167:web:7e04118a0f0cf879b7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    authDomain: 'device-streaming-edb894b1.firebaseapp.com',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );

  // =============================
  // 🤖 ANDROID
  // =============================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2TQgTv98BiTSa5b4lKNWbLFQKdJD9gwI',
    appId: '1:199751335167:android:a35c2fc7a2827698b7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );

  // =============================
  // 🍎 iOS
  // =============================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQgoGYJk-gDeUk9ZqrkPPYTEFz7FMyWQ',
    appId: '1:199751335167:ios:24c397c601f6bc9db7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
    iosBundleId: 'com.gizisehat.giziSehatMobileApp', // 🏷️ Cocokkan di Xcode
  );

  // =============================
  // 💻 macOS (pakai config iOS)
  // =============================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATQgoGYJk-gDeUk9ZqrkPPYTEFz7FMyWQ',
    appId: '1:199751335167:ios:24c397c601f6bc9db7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
    iosBundleId: 'com.gizisehat.giziSehatMobileApp',
  );

  // =============================
  // 🪟 WINDOWS
  // =============================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxrg3As4P9q7uHd1anjZPglHB2HH6mf6k',
    appId: '1:199751335167:web:77588d61a93a4f3eb7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    authDomain: 'device-streaming-edb894b1.firebaseapp.com',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );
}

// =======================================================
// 🧾 ASCII FAREWELL
// =======================================================
//
//   (⌐■_■)
//    Firebase OK
//    No Error
//
// Tips hidup Flutter Dev:
// - Kalau Firebase error → cek projectId 🧐
// - Kalau crash → cek platform config 😭
// - Kalau stres → print() dulu 😆
//
// print("🔥 Firebase Options loaded successfully!");
// =======================================================
