// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxrg3As4P9q7uHd1anjZPglHB2HH6mf6k',
    appId: '1:199751335167:web:7e04118a0f0cf879b7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    authDomain: 'device-streaming-edb894b1.firebaseapp.com',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2TQgTv98BiTSa5b4lKNWbLFQKdJD9gwI',
    appId: '1:199751335167:android:a35c2fc7a2827698b7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQgoGYJk-gDeUk9ZqrkPPYTEFz7FMyWQ',
    appId: '1:199751335167:ios:24c397c601f6bc9db7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
    iosBundleId: 'com.gizisehat.giziSehatMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATQgoGYJk-gDeUk9ZqrkPPYTEFz7FMyWQ',
    appId: '1:199751335167:ios:24c397c601f6bc9db7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
    iosBundleId: 'com.gizisehat.giziSehatMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxrg3As4P9q7uHd1anjZPglHB2HH6mf6k',
    appId: '1:199751335167:web:77588d61a93a4f3eb7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    authDomain: 'device-streaming-edb894b1.firebaseapp.com',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );
}
