// =======================================================
// 🚀 Firebase Options (Generated by FlutterFire CLI)
// =======================================================
// File ini otomatis dibuat oleh FlutterFire CLI.
// Saya cuma nambah komentar, emot dan ASCII — TIDAK mengubah logic.
//
// WARNING:
// - API keys di bawah adalah konfigurasi client-side Firebase.
// - Meski bukan credential server-side, tetap hati-hati saat
//   menaruh project ini di repo publik bersama file sensitif lainnya.
//   (Jangan taruh service account / credential rahasia di repo publik) 🔒
// =======================================================

//  _  _ ___ ___ ___ ___ ___
// | \| | __| _ \ __| __| _ \
// | .` | _||   / _|| _||   /
// |_|\_|___|_|_\___|___|_|_\
//  FlutterFire initialized — semoga lancar 🔥✨

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] untuk dipakai di app kamu.
///
/// Contoh penggunaan:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// Komentar: jangan lupa `flutterfire configure` kalau pindah project 😅
class DefaultFirebaseOptions {
  // 🔁 Pilih konfigurasi sesuai platform
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // 🌐 Web
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      // 🤖 Android
        return android;
      case TargetPlatform.iOS:
      // 🍎 iOS
        return ios;
      case TargetPlatform.macOS:
      // 💻 macOS
        return macos;
      case TargetPlatform.windows:
      // 🪟 Windows
        return windows;
      case TargetPlatform.linux:
      // 🐧 Linux belum dikonfigurasi — jalankan FlutterFire CLI lagi jika mau support
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
      // 🤷 Platform aneh
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // =============================
  // 🌐 WEB
  // =============================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxrg3As4P9q7uHd1anjZPglHB2HH6mf6k',
    appId: '1:199751335167:web:7e04118a0f0cf879b7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    authDomain: 'device-streaming-edb894b1.firebaseapp.com',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );

  // =============================
  // 🤖 ANDROID
  // =============================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2TQgTv98BiTSa5b4lKNWbLFQKdJD9gwI',
    appId: '1:199751335167:android:a35c2fc7a2827698b7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );

  // =============================
  // 🍎 iOS
  // =============================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQgoGYJk-gDeUk9ZqrkPPYTEFz7FMyWQ',
    appId: '1:199751335167:ios:24c397c601f6bc9db7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
    iosBundleId: 'com.gizisehat.giziSehatMobileApp', // 🏷️ Bundle ID — cocokkan di Xcode
  );

  // =============================
  // 💻 macOS (pakai config iOS)
  // =============================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATQgoGYJk-gDeUk9ZqrkPPYTEFz7FMyWQ',
    appId: '1:199751335167:ios:24c397c601f6bc9db7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
    iosBundleId: 'com.gizisehat.giziSehatMobileApp',
  );

  // =============================
  // 🪟 WINDOWS
  // =============================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxrg3As4P9q7uHd1anjZPglHB2HH6mf6k',
    appId: '1:199751335167:web:77588d61a93a4f3eb7e0ca',
    messagingSenderId: '199751335167',
    projectId: 'device-streaming-edb894b1',
    authDomain: 'device-streaming-edb894b1.firebaseapp.com',
    storageBucket: 'device-streaming-edb894b1.firebasestorage.app',
  );
}

// =======================================================
//   ASCII FAREWELL
// =======================================================
// Have a bug-free day! 🐞➡️🔥
//
//   .-""""-.
//  / -   -  \   <- Ini bukan error, cuma TODO
// |  .-. .-.  |
// |  | | | |  |
//  \ \o/ \o/ /
//  _/  `-'  \_
// /  \_____/  \
// \___________/
//
// Keep calm and flutter on! 🚀
